apiVersion: v1
kind: ConfigMap
metadata:
  name: costwatch-config
  namespace: costwatch
data:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "info"
  API_GATEWAY_PORT: "8000"
  RESOURCE_SCANNER_PORT: "5000"
  REDIS_PORT: "6379"
  POSTGRES_PORT: "5432"
  # Database configuration (non-sensitive)
  POSTGRES_DB: "costwatch_dev"
  POSTGRES_USER: "costwatch_user"
  # Service URLs
  RESOURCE_SCANNER_URL: "http://resource-scanner-service:5000"
  API_GATEWAY_URL: "http://api-gateway-service:8000"