apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: costwatch
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-scanner
  namespace: costwatch
spec:
  template:
    spec:
      containers:
      - name: resource-scanner
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"