apiVersion: v1
kind: Service
metadata:
  name: cost-analyzer-service
  namespace: costwatch
  labels:
    app: cost-analyzer
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: cost-analyzer